# Form implementation generated from reading ui file 'Admin_interface.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Admin_interface(object):
    def setupUi(self, Admin_interface):
        Admin_interface.setObjectName("Admin_interface")
        Admin_interface.resize(1000, 701)
        self.centralwidget = QtWidgets.QWidget(parent=Admin_interface)
        self.centralwidget.setStyleSheet("background-color: rgb(25, 11, 44);\n"
"\n"
"font-family:\"Tw Cen MT\";")
        self.centralwidget.setObjectName("centralwidget")
        self.frame_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left.setGeometry(QtCore.QRect(0, 60, 71, 641))
        self.frame_left.setStyleSheet("background-color: rgb(65, 41, 93);")
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.homeButton = QtWidgets.QPushButton(parent=self.frame_left)
        self.homeButton.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./icons/Home_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(70, 70))
        self.homeButton.setObjectName("homeButton")
        self.title_Info = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_Info.setGeometry(QtCore.QRect(0, 0, 1001, 61))
        self.title_Info.setStyleSheet("\n"
"background-color: #41295D;\n"
"")
        self.title_Info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_Info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_Info.setObjectName("title_Info")
        self.layoutWidget = QtWidgets.QWidget(parent=self.title_Info)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 226, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Icon_GachaClub = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Icon_GachaClub.setMinimumSize(QtCore.QSize(70, 60))
        self.Icon_GachaClub.setMaximumSize(QtCore.QSize(70, 60))
        self.Icon_GachaClub.setStyleSheet("background-color: none;\n"
"border: none;")
        self.Icon_GachaClub.setText("")
        self.Icon_GachaClub.setPixmap(QtGui.QPixmap("./icons/Gacha Club.png"))
        self.Icon_GachaClub.setScaledContents(True)
        self.Icon_GachaClub.setObjectName("Icon_GachaClub")
        self.horizontalLayout.addWidget(self.Icon_GachaClub)
        self.Name_app = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Name_app.setMinimumSize(QtCore.QSize(148, 35))
        self.Name_app.setMaximumSize(QtCore.QSize(148, 35))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(22)
        self.Name_app.setFont(font)
        self.Name_app.setStyleSheet("background-color:  rgb(255, 255, 255, 0);\n"
"border-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.Name_app.setObjectName("Name_app")
        self.horizontalLayout.addWidget(self.Name_app)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(390, 80, 348, 51))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.PersonalAreaLayout = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.PersonalAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.PersonalAreaLayout.setObjectName("PersonalAreaLayout")
        self.Icon_PersonalArea = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.Icon_PersonalArea.setMaximumSize(QtCore.QSize(40, 40))
        self.Icon_PersonalArea.setText("")
        self.Icon_PersonalArea.setPixmap(QtGui.QPixmap("./icons/main_icon.png"))
        self.Icon_PersonalArea.setScaledContents(True)
        self.Icon_PersonalArea.setObjectName("Icon_PersonalArea")
        self.PersonalAreaLayout.addWidget(self.Icon_PersonalArea)
        self.label_PersonalArea = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.label_PersonalArea.setMinimumSize(QtCore.QSize(300, 0))
        self.label_PersonalArea.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_PersonalArea.setFont(font)
        self.label_PersonalArea.setStyleSheet("background-color:  rgb(255, 255, 255, 0);\n"
"border-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_PersonalArea.setObjectName("label_PersonalArea")
        self.PersonalAreaLayout.addWidget(self.label_PersonalArea)
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(90, 130, 891, 371))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
"   border: 1px rgb(65, 41, 93);\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"  background-color: rgb(65, 41, 93);; \n"
"  color:rgb(255, 255, 255);\n"
"  padding: 10px;\n"
"  border: 2px solid rgb(40, 44, 52);\n"
"  border-radius: 10px;\n"
" }\n"
"\n"
" QTabBar::tab:selected {\n"
"  background-color: rgb(43, 51, 67);\n"
" }\n"
"\n"
"QTabWidget::pane { \n"
"   border: none;\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setStyleSheet("")
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.changeButton1 = QtWidgets.QPushButton(parent=self.tab_1)
        self.changeButton1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(1)
        self.changeButton1.setFont(font)
        self.changeButton1.setStyleSheet("QPushButton{\n"
"color: none;\n"
"background-color: rgb(25, 11, 44);\n"
"border: 4px solid rgb(25, 11, 44);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./icons/Change.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.changeButton1.setIcon(icon1)
        self.changeButton1.setIconSize(QtCore.QSize(30, 30))
        self.changeButton1.setObjectName("changeButton1")
        self.horizontalLayout_2.addWidget(self.changeButton1)
        self.deleteButton1 = QtWidgets.QPushButton(parent=self.tab_1)
        self.deleteButton1.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        self.deleteButton1.setFont(font)
        self.deleteButton1.setStyleSheet("QPushButton{\n"
"color: rgba(0, 0, 0, 0);\n"
"background-color: rgb(25, 11, 44);\n"
"border: 4px solid rgb(25, 11, 44);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.deleteButton1.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./icons/Delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.deleteButton1.setIcon(icon2)
        self.deleteButton1.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton1.setObjectName("deleteButton1")
        self.horizontalLayout_2.addWidget(self.deleteButton1)
        self.addButton1 = QtWidgets.QPushButton(parent=self.tab_1)
        self.addButton1.setMaximumSize(QtCore.QSize(40, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(1)
        self.addButton1.setFont(font)
        self.addButton1.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 11, 44);\n"
"border: 4px solid rgb(25, 11, 44);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("./icons/Add properties.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addButton1.setIcon(icon3)
        self.addButton1.setIconSize(QtCore.QSize(30, 30))
        self.addButton1.setObjectName("addButton1")
        self.horizontalLayout_2.addWidget(self.addButton1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableView1 = QtWidgets.QTableView(parent=self.tab_1)
        self.tableView1.setStyleSheet("\n"
"\n"
"background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 30px;\n"
"")
        self.tableView1.setObjectName("tableView1")
        self.verticalLayout.addWidget(self.tableView1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.changeButton2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.changeButton2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(1)
        self.changeButton2.setFont(font)
        self.changeButton2.setStyleSheet("QPushButton{\n"
"color: rgba(0, 0, 0, 0);\n"
"background-color: rgb(25, 11, 44);\n"
"border: 4px solid rgb(25, 11, 44);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/icons/Change.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon4.addPixmap(QtGui.QPixmap("./icons/Change.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.changeButton2.setIcon(icon4)
        self.changeButton2.setIconSize(QtCore.QSize(30, 30))
        self.changeButton2.setObjectName("changeButton2")
        self.horizontalLayout_11.addWidget(self.changeButton2)
        self.deleteButton2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.deleteButton2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        self.deleteButton2.setFont(font)
        self.deleteButton2.setStyleSheet("QPushButton{\n"
"color: rgba(0, 0, 0, 0);\n"
"background-color: rgb(25, 11, 44);\n"
"border: 4px solid rgb(25, 11, 44);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.deleteButton2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/icons/Delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon5.addPixmap(QtGui.QPixmap("./icons/Delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.deleteButton2.setIcon(icon5)
        self.deleteButton2.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton2.setObjectName("deleteButton2")
        self.horizontalLayout_11.addWidget(self.deleteButton2)
        self.addButton2 = QtWidgets.QPushButton(parent=self.tab_2)
        self.addButton2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(1)
        self.addButton2.setFont(font)
        self.addButton2.setStyleSheet("QPushButton{\n"
"background-color: rgb(25, 11, 44);\n"
"border: 4px solid rgb(25, 11, 44);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.addButton2.setIcon(icon3)
        self.addButton2.setIconSize(QtCore.QSize(30, 30))
        self.addButton2.setObjectName("addButton2")
        self.horizontalLayout_11.addWidget(self.addButton2)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_11)
        spacerItem1 = QtWidgets.QSpacerItem(328, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.tableView2 = QtWidgets.QTableView(parent=self.tab_2)
        self.tableView2.setStyleSheet("QTableView {\n"
"background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 30px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"background-color: rgb(255, 255, 255);  \n"
"color: rgb(0, 0, 0);\n"
"border: 2px solid #E9E5FF;\n"
"border-radius: 30px;\n"
"height: 50px;\n"
"font-size: 16pt;\n"
"}\n"
"")
        self.tableView2.setObjectName("tableView2")
        self.verticalLayout_5.addWidget(self.tableView2)
        self.tabWidget.addTab(self.tab_2, "")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(150, 550, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 610, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(33, 37, 43);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(43, 51, 67);  \n"
"border: 2px solid rgb(33, 37, 43);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(255, 255, 255);\n"
"background-color: rgb(33, 37, 43);;  \n"
"border: 2px solid rgb(192, 218, 255);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.tableView_Info = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView_Info.setGeometry(QtCore.QRect(330, 520, 641, 161))
        self.tableView_Info.setStyleSheet("\n"
"\n"
"background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 20px;\n"
"")
        self.tableView_Info.setObjectName("tableView_Info")
        Admin_interface.setCentralWidget(self.centralwidget)

        self.retranslateUi(Admin_interface)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Admin_interface)

    def retranslateUi(self, Admin_interface):
        _translate = QtCore.QCoreApplication.translate
        Admin_interface.setWindowTitle(_translate("Admin_interface", "MainWindow"))
        self.Name_app.setText(_translate("Admin_interface", "Gacha Club"))
        self.label_PersonalArea.setText(_translate("Admin_interface", "Администратор"))
        self.changeButton1.setText(_translate("Admin_interface", "m"))
        self.addButton1.setText(_translate("Admin_interface", "a"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Admin_interface", "Клиенты"))
        self.changeButton2.setText(_translate("Admin_interface", "m"))
        self.addButton2.setText(_translate("Admin_interface", "a"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Admin_interface", "Сессии"))
        self.pushButton.setText(_translate("Admin_interface", "Показать"))
