# Form implementation generated from reading ui file 'Registration.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(1000, 700)
        Registration.setMinimumSize(QtCore.QSize(1000, 700))
        Registration.setMaximumSize(QtCore.QSize(1000, 700))
        Registration.setSizeIncrement(QtCore.QSize(1000, 700))
        Registration.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=Registration)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:0, y2:0.517045, stop:0 rgba(2,0,36,1), stop:1 rgba(142,107,187,1));\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.title_Info = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_Info.setGeometry(QtCore.QRect(0, 0, 1000, 61))
        self.title_Info.setStyleSheet("border: 1px solid rgb(255, 255, 255);\n"
"background-color: none;\n"
"")
        self.title_Info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_Info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_Info.setObjectName("title_Info")
        self.Name_app = QtWidgets.QLabel(parent=self.title_Info)
        self.Name_app.setGeometry(QtCore.QRect(80, 10, 158, 36))
        font = QtGui.QFont()
        font.setFamily("Tw Cen  MT")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Name_app.setFont(font)
        self.Name_app.setStyleSheet("background-color:  rgb(255, 255, 255, 0);\n"
"border-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.Name_app.setObjectName("Name_app")
        self.Icon_GachaClub = QtWidgets.QLabel(parent=self.title_Info)
        self.Icon_GachaClub.setGeometry(QtCore.QRect(0, 0, 71, 61))
        self.Icon_GachaClub.setStyleSheet("background-color: none;\n"
"border: none;")
        self.Icon_GachaClub.setText("")
        self.Icon_GachaClub.setPixmap(QtGui.QPixmap("./icons/Gacha Club.png"))
        self.Icon_GachaClub.setScaledContents(True)
        self.Icon_GachaClub.setObjectName("Icon_GachaClub")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 360, 431, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.VlLayout_Registration = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.VlLayout_Registration.setContentsMargins(0, 0, 0, 0)
        self.VlLayout_Registration.setObjectName("VlLayout_Registration")
        self.lineEdit_Login = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_Login.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit_Login.setFont(font)
        self.lineEdit_Login.setStyleSheet("QLineEdit#lineEdit_Login{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_Login.setInputMask("")
        self.lineEdit_Login.setText("")
        self.lineEdit_Login.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_Login.setObjectName("lineEdit_Login")
        self.VlLayout_Registration.addWidget(self.lineEdit_Login)
        self.lineEdit_Password = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.lineEdit_Password.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit_Password.setFont(font)
        self.lineEdit_Password.setStyleSheet("QLineEdit#lineEdit_Password{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit_Password.setInputMask("")
        self.lineEdit_Password.setText("")
        self.lineEdit_Password.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit_Password.setObjectName("lineEdit_Password")
        self.VlLayout_Registration.addWidget(self.lineEdit_Password)
        self.pushButton_Enter = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.pushButton_Enter.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.pushButton_Enter.setFont(font)
        self.pushButton_Enter.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_Enter.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 83, 254);\n"
"border: 4px solid rgb(111, 83, 254);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_Enter.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_Enter.setObjectName("pushButton_Enter")
        self.VlLayout_Registration.addWidget(self.pushButton_Enter)
        self.MainIcon = QtWidgets.QLabel(parent=self.centralwidget)
        self.MainIcon.setGeometry(QtCore.QRect(390, 130, 241, 211))
        self.MainIcon.setStyleSheet("background-color: none;")
        self.MainIcon.setText("")
        self.MainIcon.setPixmap(QtGui.QPixmap("./icons/main_icon.png"))
        self.MainIcon.setScaledContents(True)
        self.MainIcon.setWordWrap(False)
        self.MainIcon.setOpenExternalLinks(False)
        self.MainIcon.setObjectName("MainIcon")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(370, 620, 251, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_Registration = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_Registration.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_Registration.setSpacing(0)
        self.horizontalLayout_Registration.setObjectName("horizontalLayout_Registration")
        self.Label_DontRegistration = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Tw Cen  MT")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Label_DontRegistration.setFont(font)
        self.Label_DontRegistration.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: none;")
        self.Label_DontRegistration.setObjectName("Label_DontRegistration")
        self.horizontalLayout_Registration.addWidget(self.Label_DontRegistration)
        self.Btn_Authorization = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget_2)
        self.Btn_Authorization.setMinimumSize(QtCore.QSize(20, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_Authorization.setFont(font)
        self.Btn_Authorization.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Btn_Authorization.setStyleSheet("QPushButton#Btn_Authorization{\n"
"color: rgb(170, 0, 0);\n"
"background-color: rgba(0, 0, 0, 0);\n"
"}")
        self.Btn_Authorization.setObjectName("Btn_Authorization")
        self.horizontalLayout_Registration.addWidget(self.Btn_Authorization)
        Registration.setCentralWidget(self.centralwidget)

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "MainWindow"))
        self.Name_app.setText(_translate("Registration", "Gacha Club"))
        self.lineEdit_Login.setPlaceholderText(_translate("Registration", "Введите логин"))
        self.lineEdit_Password.setPlaceholderText(_translate("Registration", "Введите пароль"))
        self.pushButton_Enter.setText(_translate("Registration", "Зарегистрироваться"))
        self.Label_DontRegistration.setText(_translate("Registration", "Уже зарегистрированы?"))
        self.Btn_Authorization.setText(_translate("Registration", "Войти"))
