# Form implementation generated from reading ui file 'SassionDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Session_Dialog(object):
    def setupUi(self, Session_Dialog):
        Session_Dialog.setObjectName("Session_Dialog")
        Session_Dialog.resize(427, 524)
        Session_Dialog.setMinimumSize(QtCore.QSize(427, 524))
        Session_Dialog.setMaximumSize(QtCore.QSize(427, 524))
        Session_Dialog.setStyleSheet("background-color: rgb(25, 11, 44);\n"
"\n"
"font-family:\"Tw Cen MT\";")
        self.pushButton_Enter = QtWidgets.QPushButton(parent=Session_Dialog)
        self.pushButton_Enter.setGeometry(QtCore.QRect(0, 430, 429, 41))
        self.pushButton_Enter.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.pushButton_Enter.setFont(font)
        self.pushButton_Enter.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_Enter.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 83, 254);\n"
"border: 4px solid rgb(111, 83, 254);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_Enter.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_Enter.setObjectName("pushButton_Enter")
        self.layoutWidget = QtWidgets.QWidget(parent=Session_Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 40, 421, 351))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit1 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setStyleSheet("QLineEdit#lineEdit1{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit1.setInputMask("")
        self.lineEdit1.setText("")
        self.lineEdit1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit1.setObjectName("lineEdit1")
        self.verticalLayout.addWidget(self.lineEdit1)
        self.lineEdit2 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setStyleSheet("QLineEdit#lineEdit2{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit2.setInputMask("")
        self.lineEdit2.setText("")
        self.lineEdit2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit2.setObjectName("lineEdit2")
        self.verticalLayout.addWidget(self.lineEdit2)
        self.lineEdit3 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setStyleSheet("QLineEdit#lineEdit3{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit3.setInputMask("")
        self.lineEdit3.setText("")
        self.lineEdit3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit3.setObjectName("lineEdit3")
        self.verticalLayout.addWidget(self.lineEdit3)
        self.lineEdit5 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setStyleSheet("QLineEdit#lineEdit5{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit5.setInputMask("")
        self.lineEdit5.setText("")
        self.lineEdit5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit5.setObjectName("lineEdit5")
        self.verticalLayout.addWidget(self.lineEdit5)
        self.lineEdit4 = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.lineEdit4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setStyleSheet("QLineEdit#lineEdit4{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit4.setInputMask("")
        self.lineEdit4.setText("")
        self.lineEdit4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit4.setObjectName("lineEdit4")
        self.verticalLayout.addWidget(self.lineEdit4)

        self.retranslateUi(Session_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Session_Dialog)

    def retranslateUi(self, Session_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Session_Dialog.setWindowTitle(_translate("Session_Dialog", "Dialog"))
        self.pushButton_Enter.setText(_translate("Session_Dialog", "Сохранить"))
        self.lineEdit1.setPlaceholderText(_translate("Session_Dialog", "id_Пользователь"))
        self.lineEdit2.setPlaceholderText(_translate("Session_Dialog", "Номер"))
        self.lineEdit3.setPlaceholderText(_translate("Session_Dialog", "Дата"))
        self.lineEdit5.setPlaceholderText(_translate("Session_Dialog", "время"))
        self.lineEdit4.setPlaceholderText(_translate("Session_Dialog", "Цена"))
