# Form implementation generated from reading ui file 'UserDialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_User_Dialog(object):
    def setupUi(self, User_Dialog):
        User_Dialog.setObjectName("User_Dialog")
        User_Dialog.resize(427, 524)
        User_Dialog.setMinimumSize(QtCore.QSize(427, 524))
        User_Dialog.setBaseSize(QtCore.QSize(427, 524))
        User_Dialog.setStyleSheet("background-color: rgb(25, 11, 44);\n"
"\n"
"font-family:\"Tw Cen MT\";")
        self.lineEdit1 = QtWidgets.QLineEdit(parent=User_Dialog)
        self.lineEdit1.setGeometry(QtCore.QRect(0, 30, 429, 40))
        self.lineEdit1.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit1.setFont(font)
        self.lineEdit1.setStyleSheet("QLineEdit#lineEdit1{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit1.setInputMask("")
        self.lineEdit1.setText("")
        self.lineEdit1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit1.setObjectName("lineEdit1")
        self.lineEdit2 = QtWidgets.QLineEdit(parent=User_Dialog)
        self.lineEdit2.setGeometry(QtCore.QRect(0, 90, 429, 40))
        self.lineEdit2.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit2.setFont(font)
        self.lineEdit2.setStyleSheet("QLineEdit#lineEdit2{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit2.setInputMask("")
        self.lineEdit2.setText("")
        self.lineEdit2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit2.setObjectName("lineEdit2")
        self.lineEdit3 = QtWidgets.QLineEdit(parent=User_Dialog)
        self.lineEdit3.setGeometry(QtCore.QRect(0, 160, 429, 40))
        self.lineEdit3.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit3.setFont(font)
        self.lineEdit3.setStyleSheet("QLineEdit#lineEdit3{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit3.setInputMask("")
        self.lineEdit3.setText("")
        self.lineEdit3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit3.setObjectName("lineEdit3")
        self.lineEdit4 = QtWidgets.QLineEdit(parent=User_Dialog)
        self.lineEdit4.setGeometry(QtCore.QRect(0, 290, 429, 40))
        self.lineEdit4.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit4.setFont(font)
        self.lineEdit4.setStyleSheet("QLineEdit#lineEdit4{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit4.setInputMask("")
        self.lineEdit4.setText("")
        self.lineEdit4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit4.setObjectName("lineEdit4")
        self.lineEdit5 = QtWidgets.QLineEdit(parent=User_Dialog)
        self.lineEdit5.setGeometry(QtCore.QRect(0, 220, 429, 40))
        self.lineEdit5.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit5.setFont(font)
        self.lineEdit5.setStyleSheet("QLineEdit#lineEdit5{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit5.setInputMask("")
        self.lineEdit5.setText("")
        self.lineEdit5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit5.setObjectName("lineEdit5")
        self.lineEdit6 = QtWidgets.QLineEdit(parent=User_Dialog)
        self.lineEdit6.setGeometry(QtCore.QRect(0, 360, 429, 40))
        self.lineEdit6.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.lineEdit6.setFont(font)
        self.lineEdit6.setStyleSheet("QLineEdit#lineEdit6{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"border-radius: 20px;\n"
"border: 4px solid rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.lineEdit6.setInputMask("")
        self.lineEdit6.setText("")
        self.lineEdit6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lineEdit6.setObjectName("lineEdit6")
        self.pushButton_Enter = QtWidgets.QPushButton(parent=User_Dialog)
        self.pushButton_Enter.setGeometry(QtCore.QRect(0, 440, 429, 41))
        self.pushButton_Enter.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        self.pushButton_Enter.setFont(font)
        self.pushButton_Enter.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_Enter.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(111, 83, 254);\n"
"border: 4px solid rgb(111, 83, 254);\n"
"border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_Enter.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_Enter.setObjectName("pushButton_Enter")

        self.retranslateUi(User_Dialog)
        QtCore.QMetaObject.connectSlotsByName(User_Dialog)

    def retranslateUi(self, User_Dialog):
        _translate = QtCore.QCoreApplication.translate
        User_Dialog.setWindowTitle(_translate("User_Dialog", "Dialog"))
        self.lineEdit1.setPlaceholderText(_translate("User_Dialog", "Админ"))
        self.lineEdit2.setPlaceholderText(_translate("User_Dialog", "Логин"))
        self.lineEdit3.setPlaceholderText(_translate("User_Dialog", "Пароль"))
        self.lineEdit4.setPlaceholderText(_translate("User_Dialog", "Фамилия"))
        self.lineEdit5.setPlaceholderText(_translate("User_Dialog", "Имя"))
        self.lineEdit6.setPlaceholderText(_translate("User_Dialog", "Номер телефона"))
        self.pushButton_Enter.setText(_translate("User_Dialog", "Сохранить"))
