# Form implementation generated from reading ui file 'User_interface.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_User_interface(object):
    def setupUi(self, User_interface):
        User_interface.setObjectName("User_interface")
        User_interface.resize(1002, 700)
        User_interface.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=User_interface)
        self.centralwidget.setMinimumSize(QtCore.QSize(1000, 700))
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setStyleSheet("background-color: rgb(25, 11, 44);\n"
"\n"
"font-family:\"Tw Cen MT\";")
        self.centralwidget.setObjectName("centralwidget")
        self.title_Info = QtWidgets.QFrame(parent=self.centralwidget)
        self.title_Info.setGeometry(QtCore.QRect(0, 0, 1001, 61))
        self.title_Info.setStyleSheet("\n"
"background-color: #41295D;\n"
"")
        self.title_Info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.title_Info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.title_Info.setObjectName("title_Info")
        self.layoutWidget = QtWidgets.QWidget(parent=self.title_Info)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 226, 62))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Icon_GachaClub_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Icon_GachaClub_2.setMinimumSize(QtCore.QSize(70, 60))
        self.Icon_GachaClub_2.setMaximumSize(QtCore.QSize(70, 60))
        self.Icon_GachaClub_2.setStyleSheet("background-color: none;\n"
"border: none;")
        self.Icon_GachaClub_2.setText("")
        self.Icon_GachaClub_2.setPixmap(QtGui.QPixmap("icons/Gacha Club.png"))
        self.Icon_GachaClub_2.setScaledContents(True)
        self.Icon_GachaClub_2.setObjectName("Icon_GachaClub_2")
        self.horizontalLayout.addWidget(self.Icon_GachaClub_2)
        self.Name_app_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Name_app_2.setMinimumSize(QtCore.QSize(148, 35))
        self.Name_app_2.setMaximumSize(QtCore.QSize(148, 35))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(22)
        self.Name_app_2.setFont(font)
        self.Name_app_2.setStyleSheet("background-color:  rgb(255, 255, 255, 0);\n"
"border-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.Name_app_2.setObjectName("Name_app_2")
        self.horizontalLayout.addWidget(self.Name_app_2)
        self.frame_left = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left.setGeometry(QtCore.QRect(0, 59, 71, 641))
        self.frame_left.setStyleSheet("background-color: rgb(65, 41, 93);")
        self.frame_left.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left.setObjectName("frame_left")
        self.homeButton = QtWidgets.QPushButton(parent=self.frame_left)
        self.homeButton.setGeometry(QtCore.QRect(10, 20, 51, 51))
        self.homeButton.setStyleSheet("QPushButton{\n"
"background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Home_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(70, 70))
        self.homeButton.setObjectName("homeButton")
        self.frame_left2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_left2.setGeometry(QtCore.QRect(110, 140, 361, 411))
        self.frame_left2.setStyleSheet("background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 15px;\n"
"\n"
"\n"
"")
        self.frame_left2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_left2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_left2.setObjectName("frame_left2")
        self.Name = QtWidgets.QTextEdit(parent=self.frame_left2)
        self.Name.setGeometry(QtCore.QRect(10, 30, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.Name.setFont(font)
        self.Name.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.Name.setObjectName("Name")
        self.Lastname = QtWidgets.QTextEdit(parent=self.frame_left2)
        self.Lastname.setGeometry(QtCore.QRect(10, 90, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.Lastname.setFont(font)
        self.Lastname.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.Lastname.setObjectName("Lastname")
        self.Phone_Number = QtWidgets.QTextEdit(parent=self.frame_left2)
        self.Phone_Number.setGeometry(QtCore.QRect(10, 150, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.Phone_Number.setFont(font)
        self.Phone_Number.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.Phone_Number.setObjectName("Phone_Number")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frame_left2)
        self.dateEdit.setGeometry(QtCore.QRect(10, 270, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(parent=self.frame_left2)
        self.timeEdit.setGeometry(QtCore.QRect(10, 330, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.timeEdit.setObjectName("timeEdit")
        self.labelNumber = QtWidgets.QLabel(parent=self.frame_left2)
        self.labelNumber.setGeometry(QtCore.QRect(10, 210, 341, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.labelNumber.setFont(font)
        self.labelNumber.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"color: grey;")
        self.labelNumber.setObjectName("labelNumber")
        self.comboNumber = QtWidgets.QComboBox(parent=self.frame_left2)
        self.comboNumber.setGeometry(QtCore.QRect(310, 210, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.comboNumber.setFont(font)
        self.comboNumber.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.comboNumber.setStyleSheet("QComboBox#comboNumber{\n"
"background-color: rgb(65, 41, 93, 50);\n"
"border: 1px solid rgba(255,255,255,40);\n"
"border-top-right-radius: 7px;\n"
"border-top-left-radius: 7px; \n"
"border-bottom-right-radius: 7px;\n"
"border-bottom-left-radius: 7px;\n"
"}\n"
"QComboBox::drop-down#comboNumber\n"
"{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    border: 0px;\n"
"}\n"
"")
        self.comboNumber.setMaxVisibleItems(9)
        self.comboNumber.setObjectName("comboNumber")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.comboNumber.addItem("")
        self.frame_right = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_right.setGeometry(QtCore.QRect(520, 140, 441, 411))
        self.frame_right.setStyleSheet("background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 15px;\n"
"")
        self.frame_right.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_right.setObjectName("frame_right")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_right)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 40, 411, 331))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 41))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: #E9E5FF;\n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(120, 80, 348, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.PersonalAreaLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.PersonalAreaLayout.setContentsMargins(0, 0, 0, 0)
        self.PersonalAreaLayout.setObjectName("PersonalAreaLayout")
        self.Icon_PersonalArea = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.Icon_PersonalArea.setMaximumSize(QtCore.QSize(40, 40))
        self.Icon_PersonalArea.setText("")
        self.Icon_PersonalArea.setPixmap(QtGui.QPixmap("icons/main_icon.png"))
        self.Icon_PersonalArea.setScaledContents(True)
        self.Icon_PersonalArea.setObjectName("Icon_PersonalArea")
        self.PersonalAreaLayout.addWidget(self.Icon_PersonalArea)
        self.label_PersonalArea = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_PersonalArea.setMinimumSize(QtCore.QSize(300, 0))
        self.label_PersonalArea.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_PersonalArea.setFont(font)
        self.label_PersonalArea.setStyleSheet("background-color:  rgb(255, 255, 255, 0);\n"
"border-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_PersonalArea.setObjectName("label_PersonalArea")
        self.PersonalAreaLayout.addWidget(self.label_PersonalArea)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(350, 600, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(18)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"background-color: #E9E5FF;\n"
"border: 4px solid  #E9E5FF;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(192, 218, 255);\n"
"background-color:#8E6BBB;  \n"
"border: 4px solid #8E6BBB;\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"color:rgb(192, 218, 255);\n"
"background-color: rgb(188, 177, 248); \n"
"border: 2px solid rgb(65, 41, 93);\n"
"border-radius: 10px;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(540, 90, 391, 33))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:  rgb(255, 255, 255, 0);\n"
"border-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        User_interface.setCentralWidget(self.centralwidget)

        self.retranslateUi(User_interface)
        QtCore.QMetaObject.connectSlotsByName(User_interface)

    def retranslateUi(self, User_interface):
        _translate = QtCore.QCoreApplication.translate
        User_interface.setWindowTitle(_translate("User_interface", "MainWindow"))
        self.Name_app_2.setText(_translate("User_interface", "Gacha Club"))
        self.Name.setPlaceholderText(_translate("User_interface", "Имя"))
        self.Lastname.setPlaceholderText(_translate("User_interface", "Фамилия"))
        self.Phone_Number.setPlaceholderText(_translate("User_interface", "Номер телефона"))
        self.labelNumber.setText(_translate("User_interface", "Номер места"))
        self.comboNumber.setItemText(0, _translate("User_interface", "1"))
        self.comboNumber.setItemText(1, _translate("User_interface", "2"))
        self.comboNumber.setItemText(2, _translate("User_interface", "3"))
        self.comboNumber.setItemText(3, _translate("User_interface", "4"))
        self.comboNumber.setItemText(4, _translate("User_interface", "5"))
        self.comboNumber.setItemText(5, _translate("User_interface", "6"))
        self.comboNumber.setItemText(6, _translate("User_interface", "7"))
        self.comboNumber.setItemText(7, _translate("User_interface", "8"))
        self.comboNumber.setItemText(8, _translate("User_interface", "9"))
        self.label.setText(_translate("User_interface", "Имя"))
        self.label_2.setText(_translate("User_interface", "Фамилия"))
        self.label_3.setText(_translate("User_interface", "Номер телефона"))
        self.label_PersonalArea.setText(_translate("User_interface", "Личный кабинет"))
        self.pushButton_2.setText(_translate("User_interface", "Сохранить"))
        self.label_7.setText(_translate("User_interface", "Данные игровой сессии:"))
